/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author adheraprabu
 */
public class BantuanView extends javax.swing.JFrame {

    /**
     * Creates new form BantuanView
     */
    public BantuanView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_tutup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/tutup.png"))); // NOI18N
        Button_tutup.setBorderPainted(false);
        Button_tutup.setContentAreaFilled(false);
        Button_tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_tutup.setFocusable(false);
        getContentPane().add(Button_tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 60, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/AwalUI/bantuan_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getButton_tutup() {
        return Button_tutup;
    }

    public void setButton_tutup(JButton Button_tutup) {
        this.Button_tutup = Button_tutup;
    }

    public void TutupMouseListener(MouseListener l) {
        this.Button_tutup.addMouseListener(l);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_tutup;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
