/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author adheraprabu
 */
public class BermainView extends javax.swing.JFrame {

    /**
     * Creates new form bermainView
     */
    public BermainView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public void KembaliMouseListener(MouseListener l) {
        this.Button_kembali.addMouseListener(l);
    }

    public JButton getButton_kembali() {
        return Button_kembali;
    }

    public void setButton_kembali(JButton Button_kembali) {
        this.Button_kembali = Button_kembali;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_kembali = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/TentangUI/BACK.png"))); // NOI18N
        Button_kembali.setBorderPainted(false);
        Button_kembali.setContentAreaFilled(false);
        Button_kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_kembali.setFocusable(false);
        getContentPane().add(Button_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/lahan.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BermainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BermainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BermainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BermainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BermainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_kembali;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
