/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author adheraprabu
 */
public class MulaiView extends javax.swing.JFrame {

    /**
     * Creates new form MulaiView
     */
    public MulaiView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public JLabel getBg() {
        return bg;
    }

    public void setBg(JLabel bg) {
        this.bg = bg;
    }

    public JLabel getLabel_username() {
        return Label_username;
    }

    public void setLabel_username(JLabel Label_username) {
        this.Label_username = Label_username;
    }

    public void BackMouseListener(MouseListener l) {
        this.Button_Back.addMouseListener(l);
    }

    public void HutanHujanMouseListener(MouseListener l) {
        this.Button_HutanMusim.addMouseListener(l);
    }

    public void HutanMusimMouseListener(MouseListener l) {
        this.Button_HutanMusim.addMouseListener(l);
    }

    public void NextMouseListener(MouseListener l) {
        this.Button_next.addMouseListener(l);
    }

    public void PrevMouseListener(MouseListener l) {
        this.Button_prev.addMouseListener(l);
    }

    public void PilihMouseListener(MouseListener l) {
        this.Button_Pilih.addMouseListener(l);
    }

    public JButton getButton_Back() {
        return Button_Back;
    }

    public void setButton_Back(JButton Button_Back) {
        this.Button_Back = Button_Back;
    }

    public JButton getButton_HutanMusim() {
        return Button_HutanMusim;
    }

    public void setButton_HutanMusim(JButton Button_HutanMusim) {
        this.Button_HutanMusim = Button_HutanMusim;
    }

    public JButton getButton_hujantropis() {
        return Button_hujantropis;
    }

    public void setButton_hujantropis(JButton Button_hujantropis) {
        this.Button_hujantropis = Button_hujantropis;
    }

    public JButton getButton_hutanHujan() {
        return Button_HutanHujan;
    }

    public void setButton_hutanHujan(JButton Button_hutanHujan) {
        this.Button_HutanHujan = Button_hutanHujan;
    }

    public JButton getButton_hutanMusim() {
        return Button_hutanMusim;
    }

    public void setButton_hutanMusim(JButton Button_hutanMusim) {
        this.Button_hutanMusim = Button_hutanMusim;
    }

    public JButton getButton_next() {
        return Button_next;
    }

    public void setButton_next(JButton Button_next) {
        this.Button_next = Button_next;
    }

    public JButton getButton_prev() {
        return Button_prev;
    }

    public void setButton_prev(JButton Button_prev) {
        this.Button_prev = Button_prev;
    }

    public JLabel getPilihHutan() {
        return PilihHutan;
    }

    public void setPilihHutan(JLabel PilihHutan) {
        this.PilihHutan = PilihHutan;
    }

    public JButton getButton_Pilih() {
        return Button_Pilih;
    }

    public void setButton_Pilih(JButton Button_Pilih) {
        this.Button_Pilih = Button_Pilih;
    }

    public JButton getButton_HutanHujan() {
        return Button_HutanHujan;
    }

    public void setButton_HutanHujan(JButton Button_HutanHujan) {
        this.Button_HutanHujan = Button_HutanHujan;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PilihHutan = new javax.swing.JLabel();
        Label_username = new javax.swing.JLabel();
        Button_Pilih = new javax.swing.JButton();
        Button_hujantropis = new javax.swing.JButton();
        Button_hutanMusim = new javax.swing.JButton();
        Button_Back = new javax.swing.JButton();
        Button_prev = new javax.swing.JButton();
        Button_next = new javax.swing.JButton();
        Button_HutanMusim = new javax.swing.JButton();
        Button_HutanHujan = new javax.swing.JButton();
        Label_kali = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PilihHutan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/pilih_hutanmu.png"))); // NOI18N
        getContentPane().add(PilihHutan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        Label_username.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        Label_username.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 150, 40));

        Button_Pilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/PILIH.png"))); // NOI18N
        Button_Pilih.setBorderPainted(false);
        Button_Pilih.setContentAreaFilled(false);
        Button_Pilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Pilih.setFocusable(false);
        getContentPane().add(Button_Pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, 230, -1));

        Button_hujantropis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/htn_hujan.png"))); // NOI18N
        Button_hujantropis.setToolTipText("");
        Button_hujantropis.setBorderPainted(false);
        Button_hujantropis.setContentAreaFilled(false);
        Button_hujantropis.setFocusable(false);
        getContentPane().add(Button_hujantropis, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        Button_hutanMusim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/htn_musim.png"))); // NOI18N
        Button_hutanMusim.setBorderPainted(false);
        Button_hutanMusim.setContentAreaFilled(false);
        Button_hutanMusim.setFocusable(false);
        getContentPane().add(Button_hutanMusim, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        Button_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/TentangUI/BACK.png"))); // NOI18N
        Button_Back.setBorderPainted(false);
        Button_Back.setContentAreaFilled(false);
        Button_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Back.setFocusable(false);
        getContentPane().add(Button_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, -1));

        Button_prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/LEFT.png"))); // NOI18N
        Button_prev.setToolTipText("");
        Button_prev.setBorderPainted(false);
        Button_prev.setContentAreaFilled(false);
        Button_prev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_prev.setFocusable(false);
        Button_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_prevActionPerformed(evt);
            }
        });
        getContentPane().add(Button_prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        Button_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/RIGHT.png"))); // NOI18N
        Button_next.setBorderPainted(false);
        Button_next.setContentAreaFilled(false);
        Button_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_next.setFocusable(false);
        Button_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_nextActionPerformed(evt);
            }
        });
        getContentPane().add(Button_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        Button_HutanMusim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/musim_brw.png"))); // NOI18N
        Button_HutanMusim.setBorderPainted(false);
        Button_HutanMusim.setContentAreaFilled(false);
        Button_HutanMusim.setFocusable(false);
        Button_HutanMusim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HutanMusimActionPerformed(evt);
            }
        });
        getContentPane().add(Button_HutanMusim, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        Button_HutanHujan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/hujantropis_brw.png"))); // NOI18N
        Button_HutanHujan.setBorderPainted(false);
        Button_HutanHujan.setContentAreaFilled(false);
        Button_HutanHujan.setFocusable(false);
        Button_HutanHujan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HutanHujanActionPerformed(evt);
            }
        });
        getContentPane().add(Button_HutanHujan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 590, 520));

        Label_kali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/sungai.png"))); // NOI18N
        getContentPane().add(Label_kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/bg.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_prevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_prevActionPerformed

    private void Button_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_nextActionPerformed

    private void Button_HutanHujanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HutanHujanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_HutanHujanActionPerformed

    private void Button_HutanMusimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HutanMusimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_HutanMusimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_HutanHujan;
    private javax.swing.JButton Button_HutanMusim;
    private javax.swing.JButton Button_Pilih;
    private javax.swing.JButton Button_hujantropis;
    private javax.swing.JButton Button_hutanMusim;
    private javax.swing.JButton Button_next;
    private javax.swing.JButton Button_prev;
    private javax.swing.JLabel Label_kali;
    private javax.swing.JLabel Label_username;
    private javax.swing.JLabel PilihHutan;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
