/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author adheraprabu
 */
public class MulaiView extends javax.swing.JFrame {

    /**
     * Creates new form MulaiView
     */
    public MulaiView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_prev = new javax.swing.JButton();
        Button_next = new javax.swing.JButton();
        Button_pilih = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/LEFT.png"))); // NOI18N
        Button_prev.setToolTipText("");
        Button_prev.setBorderPainted(false);
        Button_prev.setContentAreaFilled(false);
        Button_prev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_prev.setFocusable(false);
        getContentPane().add(Button_prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        Button_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/RIGHT.png"))); // NOI18N
        Button_next.setBorderPainted(false);
        Button_next.setContentAreaFilled(false);
        Button_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_next.setFocusable(false);
        getContentPane().add(Button_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        Button_pilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/PILIH.png"))); // NOI18N
        Button_pilih.setBorderPainted(false);
        Button_pilih.setContentAreaFilled(false);
        Button_pilih.setFocusable(false);
        Button_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_pilihActionPerformed(evt);
            }
        });
        getContentPane().add(Button_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/HUJAN TROPIS FULL.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_pilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_pilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MulaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MulaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MulaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MulaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MulaiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_next;
    private javax.swing.JButton Button_pilih;
    private javax.swing.JButton Button_prev;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
