/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author adheraprabu
 */
public class PanelTokoBibitView extends javax.swing.JPanel {

    /**
     * Creates new form PanelTokoPupukView
     */
    public PanelTokoBibitView() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    public void JatiMouseListener(MouseListener l) {
        this.Button_BibitJati.addMouseListener(l);
    }

    public void CemaraMouseListener(MouseListener l) {
        this.Button_BibitCemara.addMouseListener(l);
    }

    public void KapurMouseListener(MouseListener l) {
        this.Button_BibitKapur.addMouseListener(l);
    }

    public void KaretMouseListener(MouseListener l) {
        this.Button_BibitKaret.addMouseListener(l);
    }

    public void KayuHitamMouseListener(MouseListener l) {
        this.Button_BibitKayuHitam.addMouseListener(l);
    }

    public void KayuBesiMouseListener(MouseListener l) {
        this.Button_BibitKayubesi.addMouseListener(l);
    }

    public void PilangMouseListener(MouseListener l) {
        this.Button_BibitPilang.addMouseListener(l);
    }

    public void PinusMouseListener(MouseListener l) {
        this.Button_BibitPinus.addMouseListener(l);
    }

    public JButton getButton_BibitCemara() {
        return Button_BibitCemara;
    }

    public void setButton_BibitCemara(JButton Button_BibitCemara) {
        this.Button_BibitCemara = Button_BibitCemara;
    }

    public JButton getButton_BibitJati() {
        return Button_BibitJati;
    }

    public void setButton_BibitJati(JButton Button_BibitJati) {
        this.Button_BibitJati = Button_BibitJati;
    }

    public JButton getButton_BibitKapur() {
        return Button_BibitKapur;
    }

    public void setButton_BibitKapur(JButton Button_BibitKapur) {
        this.Button_BibitKapur = Button_BibitKapur;
    }

    public JButton getButton_BibitKaret() {
        return Button_BibitKaret;
    }

    public void setButton_BibitKaret(JButton Button_BibitKaret) {
        this.Button_BibitKaret = Button_BibitKaret;
    }

    public JButton getButton_BibitKayuHitam() {
        return Button_BibitKayuHitam;
    }

    public void setButton_BibitKayuHitam(JButton Button_BibitKayuHitam) {
        this.Button_BibitKayuHitam = Button_BibitKayuHitam;
    }

    public JButton getButton_BibitKayubesi() {
        return Button_BibitKayubesi;
    }

    public void setButton_BibitKayubesi(JButton Button_BibitKayubesi) {
        this.Button_BibitKayubesi = Button_BibitKayubesi;
    }

    public JButton getButton_BibitPilang() {
        return Button_BibitPilang;
    }

    public void setButton_BibitPilang(JButton Button_BibitPilang) {
        this.Button_BibitPilang = Button_BibitPilang;
    }

    public JButton getButton_BibitPinus() {
        return Button_BibitPinus;
    }

    public void setButton_BibitPinus(JButton Button_BibitPinus) {
        this.Button_BibitPinus = Button_BibitPinus;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_BibitJati = new javax.swing.JButton();
        Button_BibitCemara = new javax.swing.JButton();
        Button_BibitKapur = new javax.swing.JButton();
        Button_BibitKayubesi = new javax.swing.JButton();
        Button_BibitKayuHitam = new javax.swing.JButton();
        Button_BibitPilang = new javax.swing.JButton();
        Button_BibitPinus = new javax.swing.JButton();
        Button_BibitKaret = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_BibitJati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pohon jati.png"))); // NOI18N
        Button_BibitJati.setBorderPainted(false);
        Button_BibitJati.setContentAreaFilled(false);
        Button_BibitJati.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_BibitJati.setFocusable(false);
        Button_BibitJati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BibitJatiActionPerformed(evt);
            }
        });
        add(Button_BibitJati, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 90, 160));

        Button_BibitCemara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pohon cemara.png"))); // NOI18N
        Button_BibitCemara.setBorderPainted(false);
        Button_BibitCemara.setContentAreaFilled(false);
        Button_BibitCemara.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_BibitCemara.setFocusable(false);
        add(Button_BibitCemara, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 90, 160));

        Button_BibitKapur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pohon kapur.png"))); // NOI18N
        Button_BibitKapur.setBorderPainted(false);
        Button_BibitKapur.setContentAreaFilled(false);
        Button_BibitKapur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_BibitKapur.setFocusable(false);
        add(Button_BibitKapur, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 90, 160));

        Button_BibitKayubesi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pohon kayu besi.png"))); // NOI18N
        Button_BibitKayubesi.setBorderPainted(false);
        Button_BibitKayubesi.setContentAreaFilled(false);
        Button_BibitKayubesi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_BibitKayubesi.setFocusable(false);
        add(Button_BibitKayubesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 90, 160));

        Button_BibitKayuHitam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pohon kayu hitam.png"))); // NOI18N
        Button_BibitKayuHitam.setBorderPainted(false);
        Button_BibitKayuHitam.setContentAreaFilled(false);
        Button_BibitKayuHitam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_BibitKayuHitam.setFocusable(false);
        add(Button_BibitKayuHitam, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 90, 160));

        Button_BibitPilang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pohon pilang.png"))); // NOI18N
        Button_BibitPilang.setBorderPainted(false);
        Button_BibitPilang.setContentAreaFilled(false);
        Button_BibitPilang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_BibitPilang.setFocusable(false);
        add(Button_BibitPilang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 90, 160));

        Button_BibitPinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pohon pinus.png"))); // NOI18N
        Button_BibitPinus.setBorderPainted(false);
        Button_BibitPinus.setContentAreaFilled(false);
        Button_BibitPinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_BibitPinus.setFocusable(false);
        add(Button_BibitPinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, 160));

        Button_BibitKaret.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pohon sakura.png"))); // NOI18N
        Button_BibitKaret.setBorderPainted(false);
        Button_BibitKaret.setContentAreaFilled(false);
        Button_BibitKaret.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_BibitKaret.setFocusable(false);
        add(Button_BibitKaret, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 160));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BibitJatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BibitJatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_BibitJatiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_BibitCemara;
    private javax.swing.JButton Button_BibitJati;
    private javax.swing.JButton Button_BibitKapur;
    private javax.swing.JButton Button_BibitKaret;
    private javax.swing.JButton Button_BibitKayuHitam;
    private javax.swing.JButton Button_BibitKayubesi;
    private javax.swing.JButton Button_BibitPilang;
    private javax.swing.JButton Button_BibitPinus;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
