/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author adheraprabu
 */
public class PopUpUangKurangView extends javax.swing.JDialog {

    /**
     * Creates new form PopUpUangKurangView
     */
    public PopUpUangKurangView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        setBackground(new Color(0, 0, 0, 0));
    }

    public void TutupMouseListener(MouseListener l) {
        this.Button_Tutup.addMouseListener(l);
    }

    public JButton getButton_Tutup() {
        return Button_Tutup;
    }

    public void setButton_Tutup(JButton Button_Tutup) {
        this.Button_Tutup = Button_Tutup;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The conten of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Tutup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Tutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/tutup.png"))); // NOI18N
        Button_Tutup.setBorderPainted(false);
        Button_Tutup.setContentAreaFilled(false);
        Button_Tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Tutup.setFocusable(false);
        getContentPane().add(Button_Tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/popuptidakcukup.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Tutup;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
