/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author adheraprabu
 */
public class PopUpShopView extends javax.swing.JDialog {

    /**
     * Creates new form PopUpShopView
     */
    public PopUpShopView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public JLabel getLabel_jmlUang() {
        return Label_jmlUang;
    }

    public void setLabel_jmlUang(JLabel Label_jmlUang) {
        this.Label_jmlUang = Label_jmlUang;
    }
    
    
    public void AirMouseListener(MouseListener l) {
        this.Button_Air.addMouseListener(l);
    }
    
    public void PupukMouseListener(MouseListener l) {
        this.Button_Pupuk.addMouseListener(l);
    }
    
    public void BibitMouseListener(MouseListener l) {
        this.Button_Bibit.addMouseListener(l);
    }
    
    public void CloseMouseListener(MouseListener l) {
        this.Button_Close.addMouseListener(l);
    }

    public JButton getButton_Air() {
        return Button_Air;
    }

    public void setButton_Air(JButton Button_Air) {
        this.Button_Air = Button_Air;
    }

    public JButton getButton_Bibit() {
        return Button_Bibit;
    }

    public void setButton_Bibit(JButton Button_Bibit) {
        this.Button_Bibit = Button_Bibit;
    }

    public JButton getButton_Close() {
        return Button_Close;
    }

    public void setButton_Close(JButton Button_Close) {
        this.Button_Close = Button_Close;
    }

    public JButton getButton_Pupuk() {
        return Button_Pupuk;
    }

    public void setButton_Pupuk(JButton Button_Pupuk) {
        this.Button_Pupuk = Button_Pupuk;
    }

    public JPanel getDynamicPanel() {
        return DynamicPanel;
    }

    public void setDynamicPanel(JPanel DynamicPanel) {
        this.DynamicPanel = DynamicPanel;
    }

    public JLabel getBg() {
        return bg;
    }

    public void setBg(JLabel bg) {
        this.bg = bg;
    }

    public JLabel getBg2() {
        return bg2;
    }

    public void setBg2(JLabel bg2) {
        this.bg2 = bg2;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_jmlUang = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Button_Close = new javax.swing.JButton();
        Button_Air = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Button_Pupuk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Button_Bibit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_jmlUang.setFont(new java.awt.Font("Niagara Engraved", 1, 48)); // NOI18N
        Label_jmlUang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_jmlUang.setToolTipText("");
        getContentPane().add(Label_jmlUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 170, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Lahan/kotak_uang.png"))); // NOI18N
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Lahan/dollar.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        DynamicPanel.setOpaque(false);
        DynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 660, 480));

        jLabel4.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TOKOKU");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        Button_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/tutup.png"))); // NOI18N
        Button_Close.setBorderPainted(false);
        Button_Close.setContentAreaFilled(false);
        Button_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Close.setFocusable(false);
        getContentPane().add(Button_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        Button_Air.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/air_unselect.png"))); // NOI18N
        Button_Air.setBorderPainted(false);
        Button_Air.setContentAreaFilled(false);
        Button_Air.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Air.setFocusable(false);
        getContentPane().add(Button_Air, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/bibit_tulisan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        Button_Pupuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/pupuk_unselect.png"))); // NOI18N
        Button_Pupuk.setBorderPainted(false);
        Button_Pupuk.setContentAreaFilled(false);
        Button_Pupuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Pupuk.setFocusable(false);
        getContentPane().add(Button_Pupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/tulisan_air.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        Button_Bibit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/bibit_unselect.png"))); // NOI18N
        Button_Bibit.setToolTipText("");
        Button_Bibit.setBorderPainted(false);
        Button_Bibit.setContentAreaFilled(false);
        Button_Bibit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Bibit.setFocusable(false);
        getContentPane().add(Button_Bibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/tulisan_pupuk.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/bg-toko-04.png"))); // NOI18N
        getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Toko/bg.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Air;
    private javax.swing.JButton Button_Bibit;
    private javax.swing.JButton Button_Close;
    private javax.swing.JButton Button_Pupuk;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JLabel Label_jmlUang;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
