/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author adheraprabu
 */
public class PopUpAssetView extends javax.swing.JDialog {

    /**
     * Creates new form PopUpAssetView
     */
    public PopUpAssetView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public void CloseMouseListener(MouseListener l) {
        this.Button_close.addMouseListener(l);
    }
    public void PohonJatiMouseListener(MouseListener l) {
        this.Button_pohonJati.addMouseListener(l);
    }

    public void setButton_close(JButton Button_close) {
        this.Button_close = Button_close;
    }

    public void setButton_pohonJati(JButton Button_pohonJati) {
        this.Button_pohonJati = Button_pohonJati;
    }

    public JButton getButton_close() {
        return Button_close;
    }

    public JButton getButton_pohonJati() {
        return Button_pohonJati;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_pohonJati = new javax.swing.JButton();
        Button_close = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_pohonJati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Asset/pohon_jati.png"))); // NOI18N
        Button_pohonJati.setBorderPainted(false);
        Button_pohonJati.setContentAreaFilled(false);
        Button_pohonJati.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_pohonJati.setFocusable(false);
        getContentPane().add(Button_pohonJati, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, -1));

        Button_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Asset/back-01.png"))); // NOI18N
        Button_close.setBorderPainted(false);
        Button_close.setContentAreaFilled(false);
        Button_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_close.setFocusable(false);
        Button_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_closeActionPerformed(evt);
            }
        });
        getContentPane().add(Button_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 80));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Asset/asset.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_closeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_closeActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_close;
    private javax.swing.JButton Button_pohonJati;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
