/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author adheraprabu
 */
public class PopUpMasukkanNamaView extends javax.swing.JDialog {

    /**
     * Creates new form PopUpMasukkanNamaView
     */
    public PopUpMasukkanNamaView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        setBackground(new Color(0, 0, 0, 0));
    }

    
    public void OkMouseListener(MouseListener l) {
        this.Button_Ok.addMouseListener(l);
    }

    public JButton getButton_Ok() {
        return Button_Ok;
    }

    public void setButton_Ok(JButton Button_Ok) {
        this.Button_Ok = Button_Ok;
    }

    public JTextField getTextField_namaUaer() {
        return TextField_namaUaer;
    }

    public void setTextField_namaUaer(JTextField TextField_namaUaer) {
        this.TextField_namaUaer = TextField_namaUaer;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Ok = new javax.swing.JButton();
        TextField_namaUaer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/ok.png"))); // NOI18N
        Button_Ok.setBorderPainted(false);
        Button_Ok.setContentAreaFilled(false);
        Button_Ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Ok.setFocusable(false);
        getContentPane().add(Button_Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 90, 70));

        TextField_namaUaer.setBorder(null);
        getContentPane().add(TextField_namaUaer, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 190, 720, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/input.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Ok;
    private javax.swing.JTextField TextField_namaUaer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
