/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import View.MulaiView;

/**
 *
 * @author adheraprabu
 */
public class PopUpPilihHutanView extends javax.swing.JDialog {

    /**
     * Creates new form PopUpNewGameView
     */

    public PopUpPilihHutanView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }

    public void YaMouseListener(MouseListener l) {
        this.Button_ya.addMouseListener(l);
    }

    public void TidakMouseListener(MouseListener l) {
        this.Button_tidak.addMouseListener(l);
    }

    public JButton getButton_tidak() {
        return Button_tidak;
    }

    public void setButton_tidak(JButton Button_tidak) {
        this.Button_tidak = Button_tidak;
    }

    public JButton getButton_ya() {
        return Button_ya;
    }

    public void setButton_ya(JButton Button_ya) {
        this.Button_ya = Button_ya;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_ya = new javax.swing.JButton();
        Button_tidak = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_ya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/ya1.png"))); // NOI18N
        Button_ya.setBorderPainted(false);
        Button_ya.setContentAreaFilled(false);
        Button_ya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_ya.setFocusable(false);
        Button_ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_yaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_ya, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        Button_tidak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/tidak1.png"))); // NOI18N
        Button_tidak.setBorderPainted(false);
        Button_tidak.setContentAreaFilled(false);
        Button_tidak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_tidak.setFocusable(false);
        getContentPane().add(Button_tidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/MulaiUI/pilih_1.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_yaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_yaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpPilihHutanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpPilihHutanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpPilihHutanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpPilihHutanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopUpPilihHutanView dialog = new PopUpPilihHutanView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_tidak;
    private javax.swing.JButton Button_ya;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
